services:
  base_dades:
    image: mariadb:10.11
    container_name: servidor_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: gestio_asix
      MYSQL_USER: alumne
      MYSQL_PASSWORD: 1234
    volumes:
      - dades_mysql:/var/lib/mysql
    networks:
      - xarxa_privada
    
  gestor_web:
    image: phpmyadmin:latest
    container_name: entorn_phpmyadmin
    ports:
      - "8084:84"
    environment:
      PMA_HOST: servidor_db
    depends_on:
      - base_dades
    networks:
      - xarxa_privada

volumes:
  dades_mysql:

networks:
  xarxa_privada:
    driver: bridge

